author: Andre Bocchini
github_url: https://github.com/andrebocchini/swiftynab
source_directory: .
module_version: 3.1.4
module: SwiftYNAB
hide_documentation_coverage: true
theme: apple
readme: README.md