author: Andre Bocchini
github_url: https://github.com/andrebocchini/swiftynab
source_directory: SwiftYNAB
module_version: 2.1.2
module: SwiftYNAB
hide_documentation_coverage: true
theme: apple
readme: README.md